<?php

namespace Drupal\reviewed_posts\Form;

use Drupal\Core\Entity\ContentEntityForm;
use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\reviewed_posts\ReviewedPostsInterface;


/**
 * Form controller for Reviewed posts edit forms.
 *
 * @ingroup reviewed_posts
 */
class ReviewedPostsReviewForm extends ContentEntityForm {
  /**
   * {@inheritdoc}
   */
  public function buildForm(array $form, FormStateInterface $form_state) {
    /* @var $entity \Drupal\reviewed_posts\Entity\ReviewedPosts */
    $form = parent::buildForm($form, $form_state); //hiding fields
    $entity = $this->entity;


      $form['accept'] = [
      '#type' => 'submit',
      '#value' => $this->t('Apply'),
          '#submit' => ['::submitForm','::acceptJob']
    ];

    $form['reject'] = [
      '#type' => 'submit',
      '#value' => $this->t('Reject'),
      //'#data' => ['value'=>0],
       '#submit' => ['::submitForm','::rejectJob']
    ];



    return $form;
  }

  /**
   * {@inheritdoc}
   */

  public function ___________save(array $form, FormStateInterface $form_state) {
    $entity = $this->entity;
    $status = parent::save($form, $form_state);


    $trigger = $form_state->getTriggeringElement();
      drupal_set_message('Setting state to :'.$trigger['#data']['value']. ' ' . $status );
     // echo 'Setting state to :'.$trigger['#data']['value']. ' |' . $status;
   // die(' STOPPING HERE ');

    switch ($status) {
      case SAVED_NEW:
        drupal_set_message($this->t('Created the %label Reviewed posts.', [
          '%label' => $entity->label(),
        ]));
        break;

      default:
        drupal_set_message($this->t('Saved the %label Reviewed posts.', [
          '%label' => $entity->label(),
        ]));
    }
   // $form_state->setRedirect('entity.reviewed_posts.canonical', ['reviewed_posts' => $entity->id()]);
  }

  public function ______submitForm(array &$form, FormStateInterface $form_state)
  {

      $trigger = $form_state->getTriggeringElement();
    if ($trigger['#id'] == 'edit-reject') {
        $entity = $this->entity;

        drupal_set_message('Setting state to  dddddd' );
    }

      parent::submitForm($form, $form_state); // TODO: Change the autogenerated stub

  }



  public function rejectJob(array &$form, FormStateInterface $form_state) {
      /** @var ContentEntityInterface $entity */
      $entity = $this->entity;

      $entity->set('field_status', ReviewedPostsInterface::REJECTED);
      $entity->set('field_date_of_review', date('Y-m-d'));
      $entity->save();
  }


  public function acceptJob(array &$form, FormStateInterface $form_state) {
      /** @var ContentEntityInterface $entity */
      $entity = $this->entity;

      $entity->set('field_status', ReviewedPostsInterface::ACCEPTED);
      $entity->set('field_date_of_review', date('Y-m-d'));
      $entity->save();
  }

}
